package dev.hendrikhoemberg.dmhelper.campaign.packagev2.key;

public enum CampaignContentType {
    CAMPAIGN,
    ADVENTURE, CHAPTER, SCENE,
    MAP, TOKEN,
    ENCOUNTER, COMBATANT, COMBAT_LOG_ENTRY,
    PARTY_MEMBER, CHARACTER_SHEET, SHEET_RESOURCE,
    NOTE, QUICK_NOTE, HANDOUT,
    ASSIGNMENT, LEDGER_ENTRY, TIMELINE_EVENT,
    STATBLOCK, SPELL, CONDITION, RULE, EQUIPMENT_ITEM, MAGIC_ITEM,
    CLASS, SPECIES, BACKGROUND, FEAT,
    DICE_ROLL
}
