-- Baseline schema for DMHelper.
-- Generated from the JPA entities, matching the schema Hibernate's ddl-auto=update
-- produced up to and including the 0.0.1 release. Existing installs are stamped with
-- this version via spring.flyway.baseline-on-migrate; fresh installs execute it.

create table adventure (sort_order integer not null, created_at timestamp(6) with time zone not null, campaign_id uuid not null, id uuid not null, source_attribution varchar(500), description CLOB, name varchar(255) not null, primary key (id));
create table adventure_chapter (sort_order integer not null, adventure_id uuid not null, id uuid not null, title varchar(500) not null, intro CLOB, primary key (id));
create table adventure_scene (pinx integer, piny integer, sort_order integer not null, chapter_id uuid not null, encounter_id uuid, id uuid not null, map_id uuid, scene_key varchar(50), title varchar(500) not null, body CLOB, status enum ('DONE','UNVISITED','VISITED') not null, primary key (id));
create table background (id uuid not null, feat_ref varchar(100), source_key varchar(100) not null unique, ability_scores CLOB, description CLOB, equipment CLOB, name varchar(255) not null, skills CLOB, tools CLOB, primary key (id));
create table campaign (milestone_leveling boolean default false not null, created_at timestamp(6) with time zone not null, current_scene_id uuid, id uuid not null, description CLOB, name varchar(255) not null, settings CLOB, primary key (id));
create table character_class (hit_die varchar(10), id uuid not null, source_key varchar(100) not null unique, subclass_of varchar(100), description CLOB, features CLOB, name varchar(255) not null, proficiencies CLOB, saving_throws CLOB, spellcasting CLOB, primary key (id));
create table character_sheet (hit_dice_used integer not null, xp integer not null, background_id uuid, id uuid not null, party_member_id uuid not null unique, species_id uuid, ability_scores CLOB, class_levels CLOB, feat_refs CLOB, overrides CLOB, proficiencies CLOB, spell_slots_used CLOB, primary key (id));
create table combat_log_entry (round integer not null, created_at timestamp(6) with time zone not null, sequence bigint not null, encounter_id uuid not null, id uuid not null, combatant_id varchar(36) not null, payload CLOB, type enum ('COMBATANT_ADDED','COMBATANT_REMOVED','COMBATANT_REORDERED','CONCENTRATION_CHECK','CONCENTRATION_LOST','CONCENTRATION_SET','CONDITION_ADDED','CONDITION_REMOVED','CONDITION_TICKED','DAMAGE','DEFEATED','DICE_ROLL','ENCOUNTER_ACTIVATED','ENCOUNTER_ENDED','GROUP_SPLIT','HEAL','INITIATIVE_SET','LAIR_ACTION','LEGENDARY_ACTION','LEGENDARY_RESISTANCE','NOTE','RECHARGE','REVIVED','ROUND_ADVANCE','SESSION_END','SET_HP','SORT_ORDER','TEMP_HP','TURN_END','TURN_START') not null, primary key (id));
create table combatant (concentration_check_pending boolean not null, current_hp integer not null, defeated boolean not null, group_leader boolean not null, hidden boolean not null, initiative integer not null, legendary_actions_max integer not null, legendary_actions_used integer not null, legendary_resistances_max integer not null, legendary_resistances_used integer not null, max_hp integer not null, sort_order integer not null, temp_hp integer not null, tie_breaker integer not null, encounter_id uuid not null, id uuid not null, kind varchar(16) not null, party_member_id uuid, statblock_id uuid, token_id uuid, group_id varchar(36), concentrating_on varchar(255), conditions_json CLOB, name varchar(255) not null, notes varchar(255), recharged_abilities CLOB, primary key (id));
create table dice_roll (advantage boolean not null, disadvantage boolean not null, modifier integer not null, total integer not null, created_at timestamp(6) with time zone not null, campaign_id uuid not null, id uuid not null, encounter_id varchar(36), expression varchar(100) not null, rolls CLOB, primary key (id));
create table encounter (active_turn_index integer not null, lair_action_triggered boolean not null, round integer not null, log_sequence bigint not null, campaign_id uuid not null, id uuid not null, map_id uuid, encounter_key varchar(100), lair_action_description CLOB, lair_action_name varchar(255), name varchar(255) not null, status enum ('ACTIVE','DONE','PLANNED') not null, primary key (id));
create table equipment_item (id uuid not null, cost varchar(50), weight varchar(50), source_key varchar(100) not null unique, description CLOB, name varchar(255) not null, properties CLOB, category enum ('ARMOR','GEAR','TOOL','WEAPON') not null, primary key (id));
create table feat (id uuid not null, category varchar(50), source_key varchar(100) not null unique, prerequisite varchar(500), benefit CLOB, name varchar(255) not null, primary key (id));
create table game_map (cell_size_px integer not null, grid_height integer not null, grid_width integer not null, show_grid boolean not null, sort_order integer not null, version bigint not null, campaign_id uuid not null, grid_type varchar(16) not null, id uuid not null, movement_mode varchar(16) not null, document CLOB, name varchar(255) not null, primary key (id));
create table handout (dm_only boolean not null, presented boolean not null, campaign_id uuid not null, id uuid not null, content_type varchar(100), file_name varchar(500) not null, tags CLOB, title varchar(255) not null, primary key (id));
create table item_assignment (attuned boolean not null, quantity integer not null, campaign_id uuid not null, equipment_item_id uuid, id uuid not null, magic_item_id uuid, party_member_id uuid, custom_text varchar(500), primary key (id));
create table ledger_entry (amount numeric(38,2), in_game_day integer, in_game_month integer, in_game_year integer, timestamp timestamp(6) with time zone not null, currency varchar(10), campaign_id uuid not null, id uuid not null, item_assignment_id uuid, holder varchar(255), note CLOB, direction enum ('GAIN','SPEND'), kind enum ('GOLD','ITEM'), primary key (id));
create table magic_item (requires_attunement boolean not null, id uuid not null, category varchar(50), cost varchar(50), rarity varchar(50), type varchar(50), source_key varchar(100) not null unique, weight varchar(200), attunement_detail CLOB, description CLOB, name varchar(255) not null, primary key (id));
create table note (dm_only boolean not null, created_at timestamp(6) with time zone not null, campaign_id uuid not null, id uuid not null, title varchar(500) not null, tags varchar(1000), body CLOB, type enum ('GENERIC','LOCATION','NPC','QUEST','SESSION_LOG','SESSION_PLAN') not null, primary key (id));
create table note_link (resolved boolean not null, id uuid not null, source_note_id uuid not null, target_id uuid not null, target_type varchar(50) not null, display_text varchar(500) not null, primary key (id));
create table party_member (ac integer not null, active boolean not null, current_hp integer not null, initiative_bonus integer not null, max_hp integer not null, passive_insight integer not null, passive_investigation integer not null, passive_perception integer not null, speed integer not null, campaign_id uuid not null, id uuid not null, character_name varchar(255) not null, class_and_level varchar(255), notes CLOB, player_name varchar(255), primary key (id));
create table quick_note (created_at timestamp(6) with time zone not null, campaign_id uuid not null, id uuid not null, target_id uuid not null, target_type varchar(50) not null, body CLOB not null, primary key (id));
create table rule_section (initial_header_level integer not null, sort_order integer not null, id uuid not null, parent_key varchar(100), ruleset varchar(100), source_key varchar(100) not null unique, body CLOB, name varchar(255) not null, primary key (id));
create table scene_handout (position integer not null check ((position>=0)), handout_id uuid not null, scene_id uuid not null, primary key (position, scene_id));
create table scene_statblock (position integer not null check ((position>=0)), scene_id uuid not null, statblock_id uuid not null, primary key (position, scene_id));
create table sheet_resource (current_uses integer not null, max_uses integer not null, id uuid not null, sheet_id uuid not null, name varchar(255) not null, reset_rule enum ('LONG_REST','NEVER','SHORT_REST') not null, primary key (id));
create table sheet_spell_ref (prepared boolean not null, id uuid not null, sheet_id uuid not null, spell_id uuid not null, source_class varchar(100), primary key (id));
create table species (id uuid not null, speed varchar(50), source_key varchar(100) not null unique, description CLOB, name varchar(255) not null, size varchar(255), traits CLOB, primary key (id));
create table spell (concentration boolean not null, level integer not null, ritual boolean not null, id uuid not null, school varchar(50), casting_time varchar(100), duration varchar(100), range varchar(100), source_key varchar(100) not null unique, components varchar(200), description CLOB, higher_level CLOB, name varchar(255) not null, primary key (id));
create table srd_condition (id uuid not null, source_key varchar(100) not null unique, description CLOB, name varchar(255) not null, primary key (id));
create table stat_block (ac integer not null, cha_save integer, cha_score integer not null, con_save integer, con_score integer not null, dex_save integer, dex_score integer not null, int_save integer, int_score integer not null, str_save integer, str_score integer not null, wis_save integer, wis_score integer not null, xp integer not null, created_at timestamp(6) with time zone not null, cr varchar(10) not null, campaign_id uuid, campaign_id_fk uuid, id uuid not null, hp varchar(50) not null, alignment varchar(100), size varchar(100), source_key varchar(100), type varchar(100) not null, speed varchar(200), condition_immunities varchar(500), damage_immunities varchar(500), damage_resistances varchar(500), damage_vulnerabilities varchar(500), legendary_description varchar(500), senses varchar(500), skills varchar(500), languages varchar(1000), actions CLOB, bonus_actions CLOB, lair_actions CLOB, legendary_actions CLOB, name varchar(255) not null, reactions CLOB, traits CLOB, source enum ('CUSTOM','SRD') not null, primary key (id));
create table timeline_event (in_game_day integer not null, in_game_month integer not null, in_game_year integer not null, campaign_id uuid not null, id uuid not null, note_id uuid, body CLOB, title varchar(255) not null, primary key (id));
create table token (current_hp integer, dead boolean not null, hidden boolean not null, max_hp integer, positionx integer not null, positiony integer not null, size_cols integer not null, size_rows integer not null, color varchar(7) not null, id uuid not null, kind varchar(16) not null, map_id uuid not null, party_member_id uuid, statblock_id uuid, icon varchar(100), name varchar(255) not null, notes CLOB, primary key (id));
create index idx_adventure_campaign on adventure (campaign_id);
create index idx_chapter_adventure on adventure_chapter (adventure_id);
create index idx_scene_chapter on adventure_scene (chapter_id);
create index idx_scene_map on adventure_scene (map_id);
create index idx_scene_encounter on adventure_scene (encounter_id);
create index idx_bg_name on background (name);
create index idx_class_name on character_class (name);
create index idx_class_subclassof on character_class (subclass_of);
create index idx_log_encounter on combat_log_entry (encounter_id);
create index idx_combatant_encounter on combatant (encounter_id);
create index idx_combatant_group on combatant (group_id);
create index idx_encounter_campaign on encounter (campaign_id);
create index idx_encounter_map on encounter (map_id);
create index idx_equip_name on equipment_item (name);
create index idx_equip_category on equipment_item (category);
create index idx_feat_name on feat (name);
create index idx_feat_category on feat (category);
create index idx_gamemap_campaign on game_map (campaign_id);
create index idx_handout_campaign on handout (campaign_id);
create index idx_magic_name on magic_item (name);
create index idx_magic_rarity on magic_item (rarity);
create index idx_magic_category on magic_item (category);
create index idx_rule_name on rule_section (name);
create index idx_rule_ruleset on rule_section (ruleset);
create index idx_resource_sheet on sheet_resource (sheet_id);
create index idx_spellref_sheet on sheet_spell_ref (sheet_id);
create index idx_spellref_spell on sheet_spell_ref (spell_id);
create index idx_species_name on species (name);
create index idx_spell_name on spell (name);
create index idx_spell_level on spell (level);
create index idx_spell_school on spell (school);
create index idx_condition_name on srd_condition (name);
create index idx_statblock_source on stat_block (source);
create index idx_statblock_campaign on stat_block (campaign_id);
create index idx_statblock_name on stat_block (name);
create index idx_statblock_cr on stat_block (cr);
create index idx_statblock_type on stat_block (type);
create index idx_token_map on token (map_id);
alter table if exists adventure add constraint FKoso91ghaij2j0bn3mva5gb9k9 foreign key (campaign_id) references campaign;
alter table if exists adventure_chapter add constraint FKqqp2xgig22cpa8h6rpjpwe3fs foreign key (adventure_id) references adventure;
alter table if exists adventure_scene add constraint FKlrubi39mta5ln5snql1dwmfsw foreign key (chapter_id) references adventure_chapter;
alter table if exists adventure_scene add constraint FKrtad30i40ad6t4ls06yrc9p7f foreign key (encounter_id) references encounter;
alter table if exists adventure_scene add constraint FKf0u296fyr5bnji2btnb7m31cg foreign key (map_id) references game_map;
alter table if exists character_sheet add constraint FKcpwxibk6ml5kjuciebx13rewx foreign key (background_id) references background;
alter table if exists character_sheet add constraint FK9jvst641gq05ndqvjnfvlkh6i foreign key (party_member_id) references party_member;
alter table if exists character_sheet add constraint FK3hhx9hql8fmcq4riptx51gnai foreign key (species_id) references species;
alter table if exists combat_log_entry add constraint FKjsfic0e7533f9to51vfmg632r foreign key (encounter_id) references encounter;
alter table if exists combatant add constraint FKl35uyx5mosybn2bt3cgy7i7hk foreign key (encounter_id) references encounter;
alter table if exists combatant add constraint FKmulbtrxlghyjfbyw1g1yphy6c foreign key (party_member_id) references party_member;
alter table if exists combatant add constraint FKga8bojlgquctysh3tbcwqnqty foreign key (statblock_id) references stat_block;
alter table if exists combatant add constraint FKsi7tk9ad9t0cjv96mm0u72dyh foreign key (token_id) references token;
alter table if exists dice_roll add constraint FK609vxkxnnaw11hufvs7t7sskj foreign key (campaign_id) references campaign;
alter table if exists encounter add constraint FKls3qsepqg4kvdiourkwg2iuh7 foreign key (campaign_id) references campaign;
alter table if exists encounter add constraint FKgfttgi3944ehv4bb2ah6ghp4d foreign key (map_id) references game_map;
alter table if exists game_map add constraint FKolcrm1554qsvh3ht7dma3jbo3 foreign key (campaign_id) references campaign;
alter table if exists handout add constraint FK9noi9gug7nhjxfjtm8sxrdbdv foreign key (campaign_id) references campaign;
alter table if exists item_assignment add constraint FK651q9ue0esqypitj7pbyf4utf foreign key (campaign_id) references campaign;
alter table if exists item_assignment add constraint FKcm0idsp8vnnev2p07jhgnca7x foreign key (equipment_item_id) references equipment_item;
alter table if exists item_assignment add constraint FKp0rsnbx4idldl19k0edx7uc7g foreign key (magic_item_id) references magic_item;
alter table if exists item_assignment add constraint FKsymyqvdjwbl18tpmmue5odua4 foreign key (party_member_id) references party_member;
alter table if exists ledger_entry add constraint FK96lkdktjc1t90os966caeo870 foreign key (campaign_id) references campaign;
alter table if exists ledger_entry add constraint FK2c35lwyonh7pis0wbd4166n20 foreign key (item_assignment_id) references item_assignment;
alter table if exists note add constraint FK4t2pixgsnqoulackrcrhljdun foreign key (campaign_id) references campaign;
alter table if exists note_link add constraint FK6ertejpn9gr4vgbs4hkose2f2 foreign key (source_note_id) references note;
alter table if exists party_member add constraint FK7y9dsjri3v499t3ibyosu38p8 foreign key (campaign_id) references campaign;
alter table if exists quick_note add constraint FKswj6ppcgg9j8uxg2sfap3kt79 foreign key (campaign_id) references campaign;
alter table if exists scene_handout add constraint FKd4w9hkkypunj5ol0urmscgjqg foreign key (handout_id) references handout;
alter table if exists scene_handout add constraint FKr973q28ufjmpeth3sos91l1yx foreign key (scene_id) references adventure_scene;
alter table if exists scene_statblock add constraint FKbsq5x59it0s5buu9diqttcn44 foreign key (statblock_id) references stat_block;
alter table if exists scene_statblock add constraint FKc8kwco7w751qem4g5s26sp5on foreign key (scene_id) references adventure_scene;
alter table if exists sheet_resource add constraint FK1feru8cuvydbmd5i4mbo2gu2x foreign key (sheet_id) references character_sheet;
alter table if exists sheet_spell_ref add constraint FKa1wy0fitskyu7wi2iyig4wi69 foreign key (sheet_id) references character_sheet;
alter table if exists sheet_spell_ref add constraint FKm2h9nj4bbcfnh1cya5em70vw7 foreign key (spell_id) references spell;
alter table if exists stat_block add constraint FKp6pbsurd0yhnj4m4fajoxr1es foreign key (campaign_id_fk) references campaign;
alter table if exists timeline_event add constraint FKlotay5fwwb8o2118aefyk73rp foreign key (campaign_id) references campaign;
alter table if exists timeline_event add constraint FKo7ojmndksv5n75ry7tc7rue7m foreign key (note_id) references note;
alter table if exists token add constraint FKgfsx4vxc3tuluya5yp18v1n1u foreign key (map_id) references game_map;
alter table if exists token add constraint FKmohpwqfxgjifwq0gcd0wel2do foreign key (party_member_id) references party_member;
alter table if exists token add constraint FK3cawyx03ffnvfcyybx9geyc00 foreign key (statblock_id) references stat_block;
